### PR TITLE
Typescript conversion

### LINKED ISSUE #61: Enhancement: Typescript conversion
**Describe the bug**
In the editor, not every property is defined and generally using Typescript reduces the amount of bugs 
in the code. This will make minor problems like the button component not having every property defined disappear
as well. 

**To Reproduce**
1. Go to 'src/components/HeroSelection.jsx'
2. See error on the component

**Expected behavior**
For there not to be any warnings or error messages in the code editor (Visual Studio Code)

**Additional context**
Lots of things don't have fully definitions for types and I'd be more than happy to convert everything.

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #61 

I have only done the basics so far. I am still working on some of the event-related stuff.

### CODE REVIEW

**Comment by a2937** [comment]
Okay I think I'm ready for a review now.

File: src/App.tsx [hunk 1]
```diff
@@ -3,16 +3,17 @@ import QuizTemplate from './components/QuizTemplate';
...
-        <WelcomePage start={toggleHomePage} /> :
-        <QuizTemplate home={toggleHomePage} />
-      }
-    </>
+    {
+      isHomePage?
+        <WelcomePage start = { toggleHomePage } /> :
+  <QuizTemplate home={ toggleHomePage } />
+}
+</>
```
Comment (jdwilkin4) [inline src/App.tsx:16]: This formatting looks a little off. Please fix it using something like prettier. 

Preferred format:
```
    <>
      {isHomePage ? (
        <WelcomePage start={toggleHomePage} />
      ) : (
        <QuizTemplate home={toggleHomePage} />
      )}
    </>
```

File: src/components/Questions.tsx [hunk 2]
```diff
@@ -1,6 +1,6 @@
 import QuizModal from './QuizModal';
 
-const Questions = ({ currQuestion, questionNumber, totalQuestions, modalProps, chooseAnswer, points, choicesArr, checkAnswer }) => {
+const Questions: React.FC<{ currQuestion: { Question: string }, questionNumber: number, totalQuestions: number, modalProps: any, chooseAnswer: any, points: number, choicesArr: string[][], checkAnswer: Function}>= ({ currQuestion, questionNumber, totalQuestions, modalProps, chooseAnswer, points, choicesArr, checkAnswer }) => {
```
Comment (jdwilkin4) [inline src/components/Questions.tsx:3]: I think this would be better for readability reasons to break up this long line into smaller lines like this:

```
const Questions: React.FC<{
  currQuestion: { Question: string };
  questionNumber: number;
  totalQuestions: number;
  modalProps: any;
  chooseAnswer: any;
  points: number;
  choicesArr: string[][];
  checkAnswer: Function;
}> = ({
  currQuestion,
  questionNumber,
  totalQuestions,
  modalProps,
  chooseAnswer,
  points,
  choicesArr,
  checkAnswer,
}) => {
```

File: src/components/QuizTemplate.tsx [hunk 3]
```diff
@@ -75,12 +75,12 @@ const QuizTemplate = ({ home }) => {
...
   };
 
-  const shuffleModalResponses = (responses) => {
+  const shuffleModalResponses = (responses: any[]) => {
     let shuffleModalArr = shuffle(responses);
     return shuffleModalArr[0];
   };
 
-  const checkAnswer = (e) => {
+  const checkAnswer = (e: { target: { value: any; }; }) => {
```
Comment (jdwilkin4) [inline src/components/QuizTemplate.tsx:83]: Small thing, but I don't think you need this extra semi-colon here
```
e: { target: { value: any } }
```

File: src/index.tsx [hunk 4]
```diff
@@ -5,7 +5,7 @@ import reportWebVitals from './reportWebVitals';
 
 ReactDOM.render(
   <React.StrictMode>
-    <App />
+  <App />
```
Comment (jdwilkin4) [inline src/index.tsx:8]: The App component should be indented. 
```
  <React.StrictMode>
    <App />
  </React.StrictMode>,
```

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
Hi @a2937 ! 

Thank you for your PR.
I left a few comments concerning some formatting issues that should be cleaned up. 
There will probably have to be a seperate PR to clean up formatting and develop consistency across the board. So I'll speak with the other FCC developers about that. 
But if you could clean up those few issues I mentioned that would great 👍 
As for the typescript conversion, I was able to test everything on my end and it works well for me.

**Review by jdwilkin4 — APPROVED** [review]
LGTM! 👍

**Comment by jdwilkin4** [comment]
Congrats @a2937 on your first PR for the Developer Quiz Site.
We look forward to future contributions. 👍
