### PR TITLE
fix: replace browserRouter by hashRouter

### LINKED ISSUE #939: [Bug] - 404 from appear when refreshing browser after starting quiz
### What bug did you find in the codebase?

when  accessing `quizzes` route and then tries to refresh a window 
 the site displays 404 error

### PR DESCRIPTION
**Pull request by shootermv**
## Summary of changes
suppose to solve `refresh browser` problem

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

closes #939

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -2,9 +2,9 @@ import React from "react";
 import ReactDOM from "react-dom/client";
 import Root from "./App";
 import reportWebVitals from "./reportWebVitals";
-import { RouterProvider, createBrowserRouter } from "react-router-dom";
+import { RouterProvider, createHashRouter } from "react-router-dom";
```
Comment (jdwilkin4) [inline src/index.tsx:5]: The welcome and app test files should be updated too for consistency across the app

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
tested the build and preview locally and it works well on my end.
just need to update the test files mentioned below

**Review by jdwilkin4 — APPROVED** [review]
